public class class177 {
   public static String field1323 = "Loading world map - ";
   public static String field1324;
   public static String field1325 = "null";
   public static String field1326 = "Hidden";
   public static String field1327 = "Ok";
   public static String field1328 = "Select";
   public static String field1329 = "Continue";
   public static String field1330;
   public static String field1331 = "Please try using a different world.";
   public static String field1332;
   public static String field1333 = "Please wait - attempting to reestablish";
   public static String field1334;
   public static String field1335;
   public static String field1336;
   public static String field1337 = "Starting game engine...";
   public static String field1338 = "Prepared visibility map";
   public static String field1339;
   public static String field1340 = "Checking for updates - ";
   public static String field1341 = "Loaded update list";
   public static String field1342;
   public static String field1343 = "in serious rule breaking.";
   public static String field1344;
   public static String field1345 = "Loading title screen - ";
   public static String field1346 = "Loaded title screen";
   public static String field1347 = "Loading config - ";
   public static String field1348 = "Please use a different world.";
   public static String field1349 = "Connection lost";
   public static String field1350 = "Loaded sprites";
   public static String field1351 = "Loading textures - ";
   public static String field1352;
   public static String field1353;
   public static String field1354 = "Loading wordpack - ";
   public static String field1355;
   public static String field1356 = "Loading interfaces - ";
   public static String field1357 = "Trust this computer";
   public static String field1358 = "";
   public static String field1359;
   public static String field1361;
   public static String field1362 = "";
   public static String field1363 = "Please enter a 6-digit PIN.";
   public static String field1364 = "";
   public static String field1365 = "You have only just left another world.";
   public static String field1366 = "Your profile will be transferred in:";
   public static String field1367;
   public static String field1368 = "Connection timed out.";
   public static String field1369;
   public static String field1370 = "";
   public static String field1371 = "Error connecting to server.";
   public static String field1372;
   public static String field1373;
   public static String field1374 = "No response from server.";
   public static String field1375 = "Please try using a different world.";
   public static String field1376 = "";
   public static String field1377 = "Your account has been involved";
   public static String field1378;
   public static String field1379 = "";
   public static String field1380 = "Either your account is still logged in, or the last";
   public static String field1381;
   public static String field1382 = "Please try again later.";
   public static String field1383 = "RuneScape has been updated!";
   public static String field1384 = "Please reload this page.";
   public static String field1385 = "";
   public static String field1386 = "This world is full.";
   public static String field1387;
   public static String field1388 = "";
   public static String field1389 = "Unable to connect.";
   public static String field1390 = "Login server offline.";
   public static String field1391 = "";
   public static String field1392 = "Login limit exceeded.";
   public static String field1393 = "Too many connections from your address.";
   public static String field1394 = "";
   public static String field1395 = "Unable to connect.";
   public static String field1396 = "Bad session id.";
   public static String field1397 = "";
   public static String field1398 = "We suspect someone knows your password.";
   public static String field1399 = "Press 'change your password' on front page.";
   public static String field1400 = "";
   public static String field1401 = "You need a members account to login to this world.";
   public static String field1402 = "Please subscribe, or use a different world.";
   public static String field1403 = "";
   public static String field1404 = "Could not complete login.";
   public static String field1405;
   public static String field1406;
   public static String field1407 = "Loaded input handler";
   public static String field1408 = "Please wait 1 minute and try again.";
   public static String field1409;
   public static String field1410 = "Loaded config";
   public static String field1411 = "Please wait a few minutes before trying again.";
   public static String field1412;
   public static String field1413 = "Support Page";
   public static String field1414 = "members world and move your character";
   public static String field1415;
   public static String field1416 = "Account locked as we suspect it has been stolen.";
   public static String field1417;
   public static String field1418;
   public static String field1419;
   public static String field1420;
   public static String field1421;
   public static String field1422;
   public static String field1423 = " seconds.";
   public static String field1424;
   public static String field1425;
   public static String field1426;
   public static String field1427;
   public static String field1428;
   public static String field1429;
   public static String field1430;
   public static String field1431;
   public static String field1432;
   public static String field1433;
   public static String field1434 = "";
   public static String field1435 = "Members object";
   public static String field1436;
   public static String field1437;
   public static String field1438;
   public static String field1439;
   public static String field1440;
   public static String field1441;
   public static String field1442;
   public static String field1443;
   public static String field1444 = "Loading sprites - ";
   public static String field1445 = "Loaded interfaces";
   public static String field1446;
   public static String field1447;
   public static String field1448;
   public static String field1449;
   public static String field1450;
   public static String field1451;
   public static String field1452;
   public static String field1453;
   public static String field1454;
   public static String field1455 = "Loading - please wait.";
   public static String field1456;
   public static String field1457;
   public static String field1458;
   public static String field1459;
   public static String field1460;
   public static String field1461;
   public static String field1462;
   public static String field1463;
   public static String field1464;
   public static String field1465;
   public static String field1466;
   public static String field1467;
   public static String field1468;
   public static String field1469;
   public static String field1470;
   public static String field1471;
   public static String field1472;
   public static String field1473;
   public static String field1474;
   public static String field1475;
   public static String field1476;
   public static String field1477;
   public static String field1478;
   public static String field1479;
   public static String field1480 = "Too many login attempts.";
   public static String field1481;
   public static String field1482;
   public static String field1483 = "";
   public static String field1484;
   public static String field1485;
   public static String field1486;
   public static String field1487;
   public static String field1488;
   public static String field1489;
   public static String field1490;
   public static String field1491;
   public static String field1492;
   public static String field1493 = "world you were using has become unavailable.";
   public static String field1494;
   public static String field1495;
   public static String field1496;
   public static String field1497;
   public static String field1498;
   public static String field1499;
   public static String field1500;
   public static String field1501;
   public static String field1502 = "Loaded fonts";
   public static String field1503;
   public static String field1504;
   public static String field1505;
   public static String field1506;
   public static String field1507;
   public static String field1508;
   public static String field1509;
   public static String field1510 = "for 30 days: ";
   public static String field1511;
   public static String field1512;
   public static String field1513;
   public static String field1514;
   public static String field1515;
   public static String field1516;
   public static String field1517 = "Please try using a different world.";
   public static String field1518;
   public static String field1519;
   public static String field1520 = "Loading fonts - ";
   public static String field1521;
   public static String field1522;
   public static String field1523;
   public static String field1524;
   public static String field1525;
   public static String field1526;
   public static String field1527;
   public static String field1528;
   public static String field1529;
   public static String field1530;
   public static String field1531;
   public static String field1532;
   public static String field1533 = "Prepared sound engine";
   public static String field1534;
   public static String field1535;
   public static String field1536;
   public static String field1537;
   public static String field1538;
   public static String field1539;
   public static String field1540;
   public static String field1541;
   public static String field1542;
   public static String field1543;
   public static String field1544;
   public static String field1545;
   public static String field1546;
   public static String field1547 = "to a non-members area.";
   public static String field1548;
   public static String field1549;
   public static String field1550;
   public static String field1551;
   public static String field1552;
   public static String field1553;
   public static String field1554;
   public static String field1555;
   public static String field1556 = "Please try using a different world.";
   public static String field1557;
   public static String field1558;
   public static String field1559;
   public static String field1560;
   public static String field1561;
   public static String field1562;
   public static String field1563;
   public static String field1564;
   public static String field1565;
   public static String field1566;
   public static String field1567;
   public static String field1568 = "Loaded wordpack";
   public static String field1569;
   public static String field1570;
   public static String field1571 = "Take";
   public static String field1572;
   public static String field1573 = "Connecting to update server";
   public static String field1574;
   public static String field1575;
   public static String field1576;
   public static String field1577;
   public static String field1578;
   public static String field1579;
   public static String field1580;
   public static String field1581 = "Discard";
   public static String field1582;
   public static String field1583;
   public static String field1584;
   public static String field1585;
   public static String field1586;
   public static String field1587;
   public static String field1588;
   public static String field1589;
   public static String field1590;
   public static String field1591;
   public static String field1592;
   public static String field1593;
   public static String field1594;
   public static String field1595;
   public static String field1596;
   public static String field1597;
   public static String field1598;
   public static String field1599;
   public static String field1600;
   public static String field1601;
   public static String field1602;
   public static String field1603;
   public static String field1604;
   public static String field1605 = "";
   public static String field1606;
   public static String field1607;
   public static String field1608;
   public static String field1609;
   public static String field1610;
   public static String field1611 = "Loaded world map";
   public static String field1612;
   public static String field1613;
   public static String field1614;
   public static String field1615;
   public static String field1616;
   public static String field1617;
   public static String field1618;
   public static String field1619;
   public static String field1620;
   public static String field1621 = "To access this free world, log into a";
   public static String field1622;
   public static String field1623;
   public static String field1624;
   public static String field1625;
   public static String field1626;
   public static String field1627 = "Loaded textures";
   public static String field1628 = "The server is being updated.";
   public static String field1629;
   public static String field1630;
   public static String field1631;
   public static String field1632;
   public static String field1633;
   public static String field1634;
   public static String field1635;
   public static String field1636;
   public static String field1637;
   public static String field1638 = "Drop";
   public static String field1639;
   public static String field1640;
   public static String field1641;
   public static String field1642;
   public static String field1643;
   public static String field1644;
   public static String field1645;
   static String field1360 = "Please visit the support page for assistance.";

   static {
      field1417 = field1360;
      field1418 = "";
      field1419 = "This world is running a closed Beta.";
      field1469 = "Sorry invited players only.";
      field1421 = "Please use a different world.";
      field1422 = "Invalid loginserver requested.";
      field1525 = "Please try using a different world.";
      field1467 = "";
      field1373 = "Malformed login packet.";
      field1426 = "Please try again.";
      field1427 = "";
      field1515 = "No reply from loginserver.";
      field1429 = "Please wait 1 minute and try again.";
      field1430 = "";
      field1424 = "Error loading your profile.";
      field1432 = "Please contact customer support.";
      field1433 = "";
      field1487 = "Unexpected loginserver response.";
      field1512 = "Please try using a different world.";
      field1534 = "";
      field1437 = "This computers address has been blocked";
      field1438 = "as it was used to break our rules.";
      field1439 = "";
      field1440 = "";
      field1441 = "Service unavailable.";
      field1442 = "";
      field1443 = "";
      field1412 = "Please enter your username/email address.";
      field1471 = "";
      field1470 = "";
      field1405 = "Please enter your password.";
      field1448 = "";
      field1361 = "Your account must have a displayname set";
      field1562 = "in order to play the game.  Please set it";
      field1552 = "via the website, or the main game.";
      field1452 = "The unpaid balance on your account needs";
      field1453 = "to be resolved before you can play.";
      field1454 = field1360;
      field1619 = "Your account is currently inaccessible.";
      field1425 = "Please try again in a few minutes.";
      field1457 = "";
      field1458 = "You need to vote to play!";
      field1415 = "Visit runescape.com and vote,";
      field1460 = "and then come back here!";
      field1461 = "Sorry, but your account is not eligible to play.";
      field1462 = "For more information, please take a look at";
      field1450 = "our privacy policy.";
      field1576 = "Privacy Policy";
      field1472 = "Enter the 6-digit code generated by your";
      field1542 = "authenticator app.";
      field1626 = "";
      field1468 = "The code you entered was incorrect.";
      field1336 = "Please try again.";
      field1431 = "";
      field1614 = "Login attempt timed out.";
      field1342 = "Please try again.";
      field1473 = "";
      field1474 = "You were signed out.";
      field1580 = "Please sign in again.";
      field1476 = "";
      field1477 = "Failed to login.";
      field1478 = "Please try again.";
      field1479 = "";
      field1504 = "Unexpected server response";
      field1481 = "Please try using a different world.";
      field1451 = "";
      field1601 = " has logged in.";
      field1484 = " has logged out.";
      field1485 = "Unable to find ";
      field1486 = "Use";
      field1538 = "Examine";
      field1488 = "Attack";
      field1539 = "Choose Option";
      field1456 = " more options";
      field1491 = "Walk here";
      field1492 = "level-";
      field1630 = "skill-";
      field1465 = "Please wait...";
      field1495 = "Close";
      field1496 = " ";
      field1497 = "M";
      field1498 = "M";
      field1499 = "K";
      field1500 = "K";
      field1501 = "World";
      field1387 = "Your friend list is full. Max of 200 for free users, and 400 for members";
      field1503 = " is already on your friend list";
      field1335 = "Your ignore list is full. Max of 100 for free users, and 400 for members";
      field1505 = " is already on your ignore list";
      field1506 = "You can't add yourself to your own friend list";
      field1507 = "You can't add yourself to your own ignore list";
      field1508 = "Please remove ";
      field1509 = " from your ignore list first";
      field1604 = "Please remove ";
      field1511 = " from your friend list first";
      field1617 = "yellow:";
      field1513 = "yellow:";
      field1514 = "red:";
      field1446 = "red:";
      field1623 = "green:";
      field1367 = "green:";
      field1518 = "cyan:";
      field1519 = "cyan:";
      field1535 = "purple:";
      field1521 = "purple:";
      field1522 = "white:";
      field1523 = "white:";
      field1524 = "flash1:";
      field1436 = "flash1:";
      field1526 = "flash2:";
      field1359 = "flash2:";
      field1528 = "flash3:";
      field1566 = "flash3:";
      field1530 = "glow1:";
      field1531 = "glow1:";
      field1532 = "glow2:";
      field1369 = "glow2:";
      field1447 = "glow3:";
      field1548 = "glow3:";
      field1536 = "wave:";
      field1537 = "wave:";
      field1463 = "wave2:";
      field1475 = "wave2:";
      field1540 = "shake:";
      field1516 = "shake:";
      field1459 = "scroll:";
      field1428 = "scroll:";
      field1544 = "slide:";
      field1545 = "slide:";
      field1546 = "RuneScape is loading - please wait...";
      field1330 = "";
      field1494 = "Enter your username/email & password.";
      field1549 = "";
      field1550 = "Warning!";
      field1551 = "This is a <col=ff0000>PvP<col=ffffff> world.";
      field1541 = "Players can attack each other";
      field1553 = "almost everywhere.";
      field1554 = "This is a <col=ffff00>High Risk<col=ffffff> world.";
      field1555 = "The Protect Item prayer will";
      field1527 = "not work on this world.";
      field1332 = "This is a <col=ffff00>High Risk <col=ff0000>PvP<col=ffffff> world.";
      field1558 = "Players can attack each other almost everywhere";
      field1559 = "and the Protect Item prayer won't work.";
      field1543 = "This is a <col=00ffff>Beta<col=ffffff> world.";
      field1561 = "Your normal account will not be affected.";
      field1631 = "";
      field1563 = "Authenticator";
      field1564 = "<u=ff>Can't Log In?</u>";
      field1565 = "";
      field1420 = "Connecting to server...";
      field1567 = "";
      field1381 = "The game servers are currently being updated.";
      field1569 = "Please wait a few minutes and try again.";
      field1570 = "";
      field1560 = "";
      field1572 = "You were disconnected from the server.";
      field1529 = "";
      field1574 = "Login: ";
      field1324 = "Password: ";
      field1449 = "PIN: ";
      field1577 = "Welcome to RuneScape";
      field1578 = "New User";
      field1579 = "Existing User";
      field1632 = "Login";
      field1406 = "Cancel";
      field1582 = "Remember username";
      field1583 = "Hide username";
      field1584 = "Invalid credentials.";
      field1585 = "For accounts created after 24th November 2010, please use your";
      field1586 = "email address to login. Otherwise please login with your username.";
      field1587 = "Try again";
      field1588 = "Forgotten password?";
      field1589 = "Forgotten your password?";
      field1590 = "Username/email: ";
      field1591 = "Recover";
      field1592 = "Back";
      field1593 = "Can't login? Click here.";
      field1594 = "Still having trouble logging in?";
      field1355 = "Having trouble logging in?";
      field1596 = "";
      field1597 = "Page has opened in a new window.";
      field1598 = "(Please check your popup blocker.)";
      field1599 = "Please enter your username.";
      field1600 = "If you created your account after November";
      field1595 = "2010, this will be the creation email address.";
      field1602 = field1596;
      field1603 = field1597;
      field1339 = field1598;
      field1466 = "";
      field1606 = "Error connecting to server.";
      field1607 = "";
      field1608 = "The part of the website you are trying";
      field1609 = "to connect to is offline at the moment.";
      field1610 = "Please try again later.";
      field1624 = "Sorry, there was an error trying to";
      field1612 = "log you in to this part of the website.";
      field1613 = "Please try again later.";
      field1464 = "";
      field1615 = "Error connecting to server.";
      field1616 = "";
      field1642 = "You must enter a valid login to proceed. For accounts";
      field1618 = "created after 24th November 2010, please use your";
      field1489 = "email address. Otherwise please use your username.";
      field1620 = "Your date of birth isn't set.";
      field1490 = "Please verify your account status by";
      field1622 = "setting your date of birth.";
      field1639 = "Set Date of Birth";
      field1409 = "Your date of birth information is waiting";
      field1625 = "to be reviewed by our staff.";
      field1636 = "It will be processed shortly.";
      field1334 = "Before using this app, please read and accept our";
      field1353 = "<col=ffd200>terms of use</col>, <col=ffd200>privacy policy</col>, and <col=ffd200>end user licence</col>";
      field1629 = "<col=ffd200>agreement (EULA)</col>.";
      field1575 = "By accepting, you agree to these documents.";
      field1482 = "You must accept our terms of use, privacy policy,";
      field1378 = "and end user licence agreement to continue.";
      field1633 = "Accept";
      field1634 = "Decline";
      field1635 = "Select a world";
      field1557 = "Members only world";
      field1637 = "Free world";
      field1372 = "World";
      field1352 = "Players";
      field1640 = "Location";
      field1641 = "Type";
      field1344 = "OFF";
      field1643 = "FULL";
      field1644 = "Loading...";
      field1645 = "Click to switch";
   }
}
