public class class96 {
   public static String field1018 = "Loading world map - ";
   public static String field1019;
   public static String field1020 = "null";
   public static String field1021 = "Hidden";
   public static String field1022 = "Ok";
   public static String field1023 = "Select";
   public static String field1024 = "Continue";
   public static String field1025;
   public static String field1026 = "Please try using a different world.";
   public static String field1027;
   public static String field1028 = "Please wait - attempting to reestablish";
   public static String field1029;
   public static String field1030;
   public static String field1031;
   public static String field1032 = "Starting game engine...";
   public static String field1033 = "Prepared visibility map";
   public static String field1034;
   public static String field1035 = "Checking for updates - ";
   public static String field1036 = "Loaded update list";
   public static String field1037;
   public static String field1038 = "in serious rule breaking.";
   public static String field1039;
   public static String field1040 = "Loading title screen - ";
   public static String field1041 = "Loaded title screen";
   public static String field1042 = "Loading config - ";
   public static String field1043 = "Please use a different world.";
   public static String field1044 = "Connection lost";
   public static String field1045 = "Loaded sprites";
   public static String field1046 = "Loading textures - ";
   public static String field1047;
   public static String field1048;
   public static String field1049 = "Loading wordpack - ";
   public static String field1050;
   public static String field1051 = "Loading interfaces - ";
   public static String field1052 = "Trust this computer";
   public static String field1053 = "";
   public static String field1054;
   public static String field1056;
   public static String field1057 = "";
   public static String field1058 = "Please enter a 6-digit PIN.";
   public static String field1059 = "";
   public static String field1060 = "You have only just left another world.";
   public static String field1061 = "Your profile will be transferred in:";
   public static String field1062;
   public static String field1063 = "Connection timed out.";
   public static String field1064;
   public static String field1065 = "";
   public static String field1066 = "Error connecting to server.";
   public static String field1067;
   public static String field1068;
   public static String field1069 = "No response from server.";
   public static String field1070 = "Please try using a different world.";
   public static String field1071 = "";
   public static String field1072 = "Your account has been involved";
   public static String field1073;
   public static String field1074 = "";
   public static String field1075 = "Either your account is still logged in, or the last";
   public static String field1076;
   public static String field1077 = "Please try again later.";
   public static String field1078 = "RuneScape has been updated!";
   public static String field1079 = "Please reload this page.";
   public static String field1080 = "";
   public static String field1081 = "This world is full.";
   public static String field1082;
   public static String field1083 = "";
   public static String field1084 = "Unable to connect.";
   public static String field1085 = "Login server offline.";
   public static String field1086 = "";
   public static String field1087 = "Login limit exceeded.";
   public static String field1088 = "Too many connections from your address.";
   public static String field1089 = "";
   public static String field1090 = "Unable to connect.";
   public static String field1091 = "Bad session id.";
   public static String field1092 = "";
   public static String field1093 = "We suspect someone knows your password.";
   public static String field1094 = "Press 'change your password' on front page.";
   public static String field1095 = "";
   public static String field1096 = "You need a members account to login to this world.";
   public static String field1097 = "Please subscribe, or use a different world.";
   public static String field1098 = "";
   public static String field1099 = "Could not complete login.";
   public static String field1100;
   public static String field1101;
   public static String field1102 = "Loaded input handler";
   public static String field1103 = "Please wait 1 minute and try again.";
   public static String field1104;
   public static String field1105 = "Loaded config";
   public static String field1106 = "Please wait a few minutes before trying again.";
   public static String field1107;
   public static String field1108 = "Support Page";
   public static String field1109 = "members world and move your character";
   public static String field1110;
   public static String field1111 = "Account locked as we suspect it has been stolen.";
   public static String field1112;
   public static String field1113;
   public static String field1114;
   public static String field1115;
   public static String field1116;
   public static String field1117;
   public static String field1118 = " seconds.";
   public static String field1119;
   public static String field1120;
   public static String field1121;
   public static String field1122;
   public static String field1123;
   public static String field1124;
   public static String field1125;
   public static String field1126;
   public static String field1127;
   public static String field1128;
   public static String field1129 = "";
   public static String field1130 = "Members object";
   public static String field1131;
   public static String field1132;
   public static String field1133;
   public static String field1134;
   public static String field1135;
   public static String field1136;
   public static String field1137;
   public static String field1138;
   public static String field1139 = "Loading sprites - ";
   public static String field1140 = "Loaded interfaces";
   public static String field1141;
   public static String field1142;
   public static String field1143;
   public static String field1144;
   public static String field1145;
   public static String field1146;
   public static String field1147;
   public static String field1148;
   public static String field1149;
   public static String field1150 = "Loading - please wait.";
   public static String field1151;
   public static String field1152;
   public static String field1153;
   public static String field1154;
   public static String field1155;
   public static String field1156;
   public static String field1157;
   public static String field1158;
   public static String field1159;
   public static String field1160;
   public static String field1161;
   public static String field1162;
   public static String field1163;
   public static String field1164;
   public static String field1165;
   public static String field1166;
   public static String field1167;
   public static String field1168;
   public static String field1169;
   public static String field1170;
   public static String field1171;
   public static String field1172;
   public static String field1173;
   public static String field1174;
   public static String field1175 = "Too many login attempts.";
   public static String field1176;
   public static String field1177;
   public static String field1178 = "";
   public static String field1179;
   public static String field1180;
   public static String field1181;
   public static String field1182;
   public static String field1183;
   public static String field1184;
   public static String field1185;
   public static String field1186;
   public static String field1187;
   public static String field1188 = "world you were using has become unavailable.";
   public static String field1189;
   public static String field1190;
   public static String field1191;
   public static String field1192;
   public static String field1193;
   public static String field1194;
   public static String field1195;
   public static String field1196;
   public static String field1197 = "Loaded fonts";
   public static String field1198;
   public static String field1199;
   public static String field1200;
   public static String field1201;
   public static String field1202;
   public static String field1203;
   public static String field1204;
   public static String field1205 = "for 30 days: ";
   public static String field1206;
   public static String field1207;
   public static String field1208;
   public static String field1209;
   public static String field1210;
   public static String field1211;
   public static String field1212 = "Please try using a different world.";
   public static String field1213;
   public static String field1214;
   public static String field1215 = "Loading fonts - ";
   public static String field1216;
   public static String field1217;
   public static String field1218;
   public static String field1219;
   public static String field1220;
   public static String field1221;
   public static String field1222;
   public static String field1223;
   public static String field1224;
   public static String field1225;
   public static String field1226;
   public static String field1227;
   public static String field1228 = "Prepared sound engine";
   public static String field1229;
   public static String field1230;
   public static String field1231;
   public static String field1232;
   public static String field1233;
   public static String field1234;
   public static String field1235;
   public static String field1236;
   public static String field1237;
   public static String field1238;
   public static String field1239;
   public static String field1240;
   public static String field1241;
   public static String field1242 = "to a non-members area.";
   public static String field1243;
   public static String field1244;
   public static String field1245;
   public static String field1246;
   public static String field1247;
   public static String field1248;
   public static String field1249;
   public static String field1250;
   public static String field1251 = "Please try using a different world.";
   public static String field1252;
   public static String field1253;
   public static String field1254;
   public static String field1255;
   public static String field1256;
   public static String field1257;
   public static String field1258;
   public static String field1259;
   public static String field1260;
   public static String field1261;
   public static String field1262;
   public static String field1263 = "Loaded wordpack";
   public static String field1264;
   public static String field1265;
   public static String field1266 = "Take";
   public static String field1267;
   public static String field1268 = "Connecting to update server";
   public static String field1269;
   public static String field1270;
   public static String field1271;
   public static String field1272;
   public static String field1273;
   public static String field1274;
   public static String field1275;
   public static String field1276 = "Discard";
   public static String field1277;
   public static String field1278;
   public static String field1279;
   public static String field1280;
   public static String field1281;
   public static String field1282;
   public static String field1283;
   public static String field1284;
   public static String field1285;
   public static String field1286;
   public static String field1287;
   public static String field1288;
   public static String field1289;
   public static String field1290;
   public static String field1291;
   public static String field1292;
   public static String field1293;
   public static String field1294;
   public static String field1295;
   public static String field1296;
   public static String field1297;
   public static String field1298;
   public static String field1299;
   public static String field1300 = "";
   public static String field1301;
   public static String field1302;
   public static String field1303;
   public static String field1304;
   public static String field1305;
   public static String field1306 = "Loaded world map";
   public static String field1307;
   public static String field1308;
   public static String field1309;
   public static String field1310;
   public static String field1311;
   public static String field1312;
   public static String field1313;
   public static String field1314;
   public static String field1315;
   public static String field1316 = "To access this free world, log into a";
   public static String field1317;
   public static String field1318;
   public static String field1319;
   public static String field1320;
   public static String field1321;
   public static String field1322 = "Loaded textures";
   public static String field1323 = "The server is being updated.";
   public static String field1324;
   public static String field1325;
   public static String field1326;
   public static String field1327;
   public static String field1328;
   public static String field1329;
   public static String field1330;
   public static String field1331;
   public static String field1332;
   public static String field1333 = "Drop";
   public static String field1334;
   public static String field1335;
   public static String field1336;
   public static String field1337;
   public static String field1338;
   public static String field1339;
   public static String field1340;
   static String field1055 = "Please visit the support page for assistance.";

   static {
      field1112 = field1055;
      field1113 = "";
      field1114 = "This world is running a closed Beta.";
      field1164 = "Sorry invited players only.";
      field1116 = "Please use a different world.";
      field1117 = "Invalid loginserver requested.";
      field1220 = "Please try using a different world.";
      field1162 = "";
      field1068 = "Malformed login packet.";
      field1121 = "Please try again.";
      field1122 = "";
      field1210 = "No reply from loginserver.";
      field1124 = "Please wait 1 minute and try again.";
      field1125 = "";
      field1119 = "Error loading your profile.";
      field1127 = "Please contact customer support.";
      field1128 = "";
      field1182 = "Unexpected loginserver response.";
      field1207 = "Please try using a different world.";
      field1229 = "";
      field1132 = "This computers address has been blocked";
      field1133 = "as it was used to break our rules.";
      field1134 = "";
      field1135 = "";
      field1136 = "Service unavailable.";
      field1137 = "";
      field1138 = "";
      field1107 = "Please enter your username/email address.";
      field1166 = "";
      field1165 = "";
      field1100 = "Please enter your password.";
      field1143 = "";
      field1056 = "Your account must have a displayname set";
      field1257 = "in order to play the game.  Please set it";
      field1247 = "via the website, or the main game.";
      field1147 = "The unpaid balance on your account needs";
      field1148 = "to be resolved before you can play.";
      field1149 = field1055;
      field1314 = "Your account is currently inaccessible.";
      field1120 = "Please try again in a few minutes.";
      field1152 = "";
      field1153 = "You need to vote to play!";
      field1110 = "Visit runescape.com and vote,";
      field1155 = "and then come back here!";
      field1156 = "Sorry, but your account is not eligible to play.";
      field1157 = "For more information, please take a look at";
      field1145 = "our privacy policy.";
      field1271 = "Privacy Policy";
      field1167 = "Enter the 6-digit code generated by your";
      field1237 = "authenticator app.";
      field1321 = "";
      field1163 = "The code you entered was incorrect.";
      field1031 = "Please try again.";
      field1126 = "";
      field1309 = "Login attempt timed out.";
      field1037 = "Please try again.";
      field1168 = "";
      field1169 = "You were signed out.";
      field1275 = "Please sign in again.";
      field1171 = "";
      field1172 = "Failed to login.";
      field1173 = "Please try again.";
      field1174 = "";
      field1199 = "Unexpected server response";
      field1176 = "Please try using a different world.";
      field1146 = "";
      field1296 = " has logged in.";
      field1179 = " has logged out.";
      field1180 = "Unable to find ";
      field1181 = "Use";
      field1233 = "Examine";
      field1183 = "Attack";
      field1234 = "Choose Option";
      field1151 = " more options";
      field1186 = "Walk here";
      field1187 = "level-";
      field1325 = "skill-";
      field1160 = "Please wait...";
      field1190 = "Close";
      field1191 = " ";
      field1192 = "M";
      field1193 = "M";
      field1194 = "K";
      field1195 = "K";
      field1196 = "World";
      field1082 = "Your friend list is full. Max of 200 for free users, and 400 for members";
      field1198 = " is already on your friend list";
      field1030 = "Your ignore list is full. Max of 100 for free users, and 400 for members";
      field1200 = " is already on your ignore list";
      field1201 = "You can't add yourself to your own friend list";
      field1202 = "You can't add yourself to your own ignore list";
      field1203 = "Please remove ";
      field1204 = " from your ignore list first";
      field1299 = "Please remove ";
      field1206 = " from your friend list first";
      field1312 = "yellow:";
      field1208 = "yellow:";
      field1209 = "red:";
      field1141 = "red:";
      field1318 = "green:";
      field1062 = "green:";
      field1213 = "cyan:";
      field1214 = "cyan:";
      field1230 = "purple:";
      field1216 = "purple:";
      field1217 = "white:";
      field1218 = "white:";
      field1219 = "flash1:";
      field1131 = "flash1:";
      field1221 = "flash2:";
      field1054 = "flash2:";
      field1223 = "flash3:";
      field1261 = "flash3:";
      field1225 = "glow1:";
      field1226 = "glow1:";
      field1227 = "glow2:";
      field1064 = "glow2:";
      field1142 = "glow3:";
      field1243 = "glow3:";
      field1231 = "wave:";
      field1232 = "wave:";
      field1158 = "wave2:";
      field1170 = "wave2:";
      field1235 = "shake:";
      field1211 = "shake:";
      field1154 = "scroll:";
      field1123 = "scroll:";
      field1239 = "slide:";
      field1240 = "slide:";
      field1241 = "RuneScape is loading - please wait...";
      field1025 = "";
      field1189 = "Enter your username/email & password.";
      field1244 = "";
      field1245 = "Warning!";
      field1246 = "This is a <col=ff0000>PvP<col=ffffff> world.";
      field1236 = "Players can attack each other";
      field1248 = "almost everywhere.";
      field1249 = "This is a <col=ffff00>High Risk<col=ffffff> world.";
      field1250 = "The Protect Item prayer will";
      field1222 = "not work on this world.";
      field1027 = "This is a <col=ffff00>High Risk <col=ff0000>PvP<col=ffffff> world.";
      field1253 = "Players can attack each other almost everywhere";
      field1254 = "and the Protect Item prayer won't work.";
      field1238 = "This is a <col=00ffff>Beta<col=ffffff> world.";
      field1256 = "Your normal account will not be affected.";
      field1326 = "";
      field1258 = "Authenticator";
      field1259 = "<u=ff>Can't Log In?</u>";
      field1260 = "";
      field1115 = "Connecting to server...";
      field1262 = "";
      field1076 = "The game servers are currently being updated.";
      field1264 = "Please wait a few minutes and try again.";
      field1265 = "";
      field1255 = "";
      field1267 = "You were disconnected from the server.";
      field1224 = "";
      field1269 = "Login: ";
      field1019 = "Password: ";
      field1144 = "PIN: ";
      field1272 = "Welcome to RuneScape";
      field1273 = "New User";
      field1274 = "Existing User";
      field1327 = "Login";
      field1101 = "Cancel";
      field1277 = "Remember username";
      field1278 = "Hide username";
      field1279 = "Invalid credentials.";
      field1280 = "For accounts created after 24th November 2010, please use your";
      field1281 = "email address to login. Otherwise please login with your username.";
      field1282 = "Try again";
      field1283 = "Forgotten password?";
      field1284 = "Forgotten your password?";
      field1285 = "Username/email: ";
      field1286 = "Recover";
      field1287 = "Back";
      field1288 = "Can't login? Click here.";
      field1289 = "Still having trouble logging in?";
      field1050 = "Having trouble logging in?";
      field1291 = "";
      field1292 = "Page has opened in a new window.";
      field1293 = "(Please check your popup blocker.)";
      field1294 = "Please enter your username.";
      field1295 = "If you created your account after November";
      field1290 = "2010, this will be the creation email address.";
      field1297 = field1291;
      field1298 = field1292;
      field1034 = field1293;
      field1161 = "";
      field1301 = "Error connecting to server.";
      field1302 = "";
      field1303 = "The part of the website you are trying";
      field1304 = "to connect to is offline at the moment.";
      field1305 = "Please try again later.";
      field1319 = "Sorry, there was an error trying to";
      field1307 = "log you in to this part of the website.";
      field1308 = "Please try again later.";
      field1159 = "";
      field1310 = "Error connecting to server.";
      field1311 = "";
      field1337 = "You must enter a valid login to proceed. For accounts";
      field1313 = "created after 24th November 2010, please use your";
      field1184 = "email address. Otherwise please use your username.";
      field1315 = "Your date of birth isn't set.";
      field1185 = "Please verify your account status by";
      field1317 = "setting your date of birth.";
      field1334 = "Set Date of Birth";
      field1104 = "Your date of birth information is waiting";
      field1320 = "to be reviewed by our staff.";
      field1331 = "It will be processed shortly.";
      field1029 = "Before using this app, please read and accept our";
      field1048 = "<col=ffd200>terms of use</col>, <col=ffd200>privacy policy</col>, and <col=ffd200>end user licence</col>";
      field1324 = "<col=ffd200>agreement (EULA)</col>.";
      field1270 = "By accepting, you agree to these documents.";
      field1177 = "You must accept our terms of use, privacy policy,";
      field1073 = "and end user licence agreement to continue.";
      field1328 = "Accept";
      field1329 = "Decline";
      field1330 = "Select a world";
      field1252 = "Members only world";
      field1332 = "Free world";
      field1067 = "World";
      field1047 = "Players";
      field1335 = "Location";
      field1336 = "Type";
      field1039 = "OFF";
      field1338 = "FULL";
      field1339 = "Loading...";
      field1340 = "Click to switch";
   }
}
